version: '3'
services:
  event-service-gui:
    build: .
    image: ghcr.io/langrenn-sprint/event-service-gui:test
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - HOST_PORT=8080
      - EVENTS_HOST_SERVER=event-service
      - EVENTS_HOST_PORT=8080
      - RACE_HOST_SERVER=race-service
      - RACE_HOST_PORT=8080
      - COMPETITION_FORMAT_HOST_SERVER=competition-format-service
      - COMPETITION_FORMAT_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - ERROR_FILE=error.log
    volumes:
      - type: bind
        source: ${ERROR_FILE}
        target: /app/${ERROR_FILE}
    depends_on:
      - "event-service"
      - "competition-format-service"
      - "race-service"
      - "user-service"
  event-service:
    image: ghcr.io/langrenn-sprint/event-service:latest
    ports:
      - "8082:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - COMPETITION_FORMAT_HOST_SERVER=competition-format-service
      - COMPETITION_FORMAT_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "mongodb"
  race-service:
    image: ghcr.io/langrenn-sprint/race-service:latest
    ports:
      - "8088:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - COMPETITION_FORMAT_HOST_SERVER=competition-format-service
      - COMPETITION_FORMAT_HOST_PORT=8080
      - EVENTS_HOST_SERVER=event-service
      - EVENTS_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "mongodb"
  competition-format-service:
    image: ghcr.io/langrenn-sprint/competition-format-service:latest
    ports:
      - 8094:8080
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
      - user-service
      - mongodb
  user-service:
    image: ghcr.io/langrenn-sprint/user-service:latest
    ports:
      - "8086:8080"
    environment:
      - JWT_EXP_DELTA_SECONDS=${JWT_EXP_DELTA_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
