version: '3'
services:
  event-service-gui:
    build: .
    image: gcr.io/langrenn-sprint/event-service-gui:test
    ports:
      - "8080:8080"
    environment:
    - HOST_PORT=8080
    - EVENT_SERVICE_HOST=event-service
    - EVENT_SERVICE_PORT=8082
    depends_on:
      - "event-service"
  event-service:
    image: gcr.io/langrenn-sprint/event-service:latest
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=user
      - DB_PASSWORD=secret
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
