[tool.poetry]
name = "event-service-gui"
version = "0.1.0"
description = "Webserver serving startlists and results"
authors = ["Stig B. Dørmænen <stigbd@gmail.com>", "Heming Harnæs <heming.harnaes@gmail.com"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/langrenn-sprint"
repository = "https://github.com/langrenn-sprint/event-service-gui"
classifiers=[
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = "^3.7  "
gunicorn = "^20.0.4"
aiohttp = "^3.7.2"
python-dotenv = "^0.15.0"
requests = "^2.25.0"
aiohttp-jinja2 = "^1.4.2"
motor = "^2.3.0"
aioresponses = "^0.7.2"
PyJWT = "^2.1.0"
multidict = "^5.1.0"
jwt = "^1.2.0"
aiohttp-session = "^2.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
coverage = {extras = ["toml"], version = "^5.3"}
pytest-dotenv = "^0.5.2"
pytest-docker = "^0.10.1"
pytest-cov = "^2.10.1"
docker-compose = "^1.27.4"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
pep8-naming = "^0.11.1"
safety = "^1.9.0"
mypy = "^0.790"
flake8-annotations = "^2.4.1"
codecov = "^2.1.10"
pytest-mock = "^3.3.1"
pytest-aiohttp = "^0.3.0"
aiohttp-devtools = "^0.13.1"
pytest-asyncio = "^0.14.0"
aioresponses = "^0.7.2"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = false
source = ["event_service_gui"]
omit = ["*gunicorn_config.py"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
